export const categories = [
  {
    _id: '1',
    name: 'Technology',
    code: 'tech',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 1200,
  },
  {
    _id: '2',
    name: 'Finance',
    code: 'finance',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 900,
  },
  {
    _id: '3',
    name: 'Healthcare',
    code: 'healthcare',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 1500,
  },
  {
    _id: '4',
    name: 'Education',
    code: 'education',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 800,
  },
  {
    _id: '5',
    name: 'Engineering',
    code: 'engineering',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 1100,
  },
  {
    _id: '6',
    name: 'Marketing',
    code: 'marketing',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 850,
  },
  {
    _id: '7',
    name: 'Sales',
    code: 'sales',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 1300,
  },
  {
    _id: '8',
    name: 'Design',
    code: 'design',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 700,
  },
  {
    _id: '9',
    name: 'Service',
    code: 'service',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 600,
  },
  {
    _id: '10',
    name: 'Human Resources',
    code: 'hr',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 500,
  },
  {
    _id: '11',
    name: 'Legal',
    code: 'legal',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 400,
  },
  {
    _id: '12',
    name: 'Construction',
    code: 'construction',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 300,
  },
  {
    _id: '13',
    name: 'Hospitality',
    code: 'hospitality',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 1000,
  },
  {
    _id: '14',
    name: 'Logistics',
    code: 'logistics',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 950,
  },
  {
    _id: '15',
    name: 'Administration',
    code: 'admin',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 650,
  },
  {
    _id: '16',
    name: 'Science',
    code: 'science',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 550,
  },
  {
    _id: '17',
    name: 'Media',
    code: 'media',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 450,
  },
  {
    _id: '18',
    name: 'Remote',
    code: 'remote',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 2000,
  },
  {
    _id: '19',
    name: 'Government',
    code: 'government',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 350,
  },
  {
    _id: '20',
    name: 'Real Estate',
    code: 'real-estate',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 300,
  },
  {
    _id: '21',
    name: 'Retail',
    code: 'retail',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 800,
  },
  {
    _id: '22',
    name: 'Manufacturing',
    code: 'manufacturing',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 700,
  },
  {
    _id: '23',
    name: 'Transportation',
    code: 'transportation',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 600,
  },
  {
    _id: '24',
    name: 'Nonprofit',
    code: 'nonprofit',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 400,
  },
  {
    _id: '25',
    name: 'Telecommunications',
    code: 'telecom',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 350,
  },
  {
    _id: '26',
    name: 'Security',
    code: 'security',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 300,
  },
  {
    _id: '27',
    name: 'Fashion',
    code: 'fashion',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 250,
  },
  {
    _id: '28',
    name: 'Food & Beverage',
    code: 'food-beverage',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 450,
  },
  {
    _id: '29',
    name: 'Arts',
    code: 'arts',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 200,
  },
  {
    _id: '30',
    name: 'Events',
    code: 'events',
    icon: 'FaChartPie',
    iconFamily: 'fa',
    totalJobs: 300,
  },
];
